spring.application.name=java_analyzer
analyzer.summary_file=RESULT.md


#Maven Repository
maven.http.timeout_secs=10



#OpenAI
openai.api_key=${OPENAI_API_KEY}
openai.model=gpt-4.1-mini
openai.temperature=0.1
openai.max_tokens=4000
openai.http.timeout_secs=60